### ISSUE TITLE
Build error with OpenSSL 1.0.1j

### ISSUE THREAD

**Issue by towynlin** [rubysl/rubysl-openssl#10]
Log here: https://gist.github.com/towynlin/78222211687fdbb9a3c3

Initial errors are

```
In file included from openssl_missing.c:22:
./openssl_missing.h:71:6: error: conflicting types for 'HMAC_CTX_copy'
void HMAC_CTX_copy(HMAC_CTX *out, HMAC_CTX *in);
     ^
/usr/local/Cellar/openssl/1.0.1j/include/openssl/hmac.h:102:5: note: previous declaration is here
int HMAC_CTX_copy(HMAC_CTX *dctx, HMAC_CTX *sctx);
    ^
```

and

```
In file included from openssl_missing.c:22:
./openssl_missing.h:95:5: error: conflicting types for 'EVP_CIPHER_CTX_copy'
int EVP_CIPHER_CTX_copy(EVP_CIPHER_CTX *out, EVP_CIPHER_CTX *in);
    ^
/usr/local/Cellar/openssl/1.0.1j/include/openssl/evp.h:502:5: note: previous declaration is here
int EVP_CIPHER_CTX_copy(EVP_CIPHER_CTX *out, const EVP_CIPHER_CTX *in);
    ^
```

with the same error repeated for those two functions in openssl_missing.c.  As a quick hack I tried just ignoring those by adding `#define` before each clause to avoid the redefinitions, but there were more errors in other files.

**Comment by brixen** [comment]
@towynlin unfortunately, we're not going to be able to fix this. You're trying to use a version of the compiler that is incompatible with the version of the VM you're running. We're trying stabilize this, so building 2.4.0+ with 2.3.0, or building 2.4.1+ with 2.4.0, etc should be working.

We're also going to remove the dependency on Ruby to build Rubinius, so this issue will go away completely. Sorry for the trouble in the meantime.

**Comment by towynlin** [comment]
No worries at all; sounds like a good plan. My current default ruby is rbx 2.4.1, which installed via ruby-build without issue. :+1:
