### ISSUE TITLE
Superclass mismatch: OpenSSL::Cipher != OpenSSL::Cipher::Cipher (TypeError)

### ISSUE THREAD

**Issue by tak1n** [rubysl/rubysl-openssl#13]
Reopen & ported from https://github.com/rubinius/rubinius/issues/2806, because for @maokomioko this issue occurs again.

@maokomioko can you provide a reproducable way to trigger this?

```
~ ❯❯❯ chruby rbx
~ ❯❯❯ ruby -v
rubinius 2.5.8.c21 (2.1.0 4eec62a0 2015-09-22 3.5.0 JI) [x86_64-linux-gnu]
~ ❯❯❯ gem list rubysl-openssl

*** LOCAL GEMS ***

rubysl-openssl (2.3.0)
~ ❯❯❯ irb
irb(main):001:0> require 'openssl'
=> true
irb(main):003:0> cipher = OpenSSL::Cipher.new('AES-128-CBC')
=> #<OpenSSL::Cipher:0x47f8>
irb(main):004:0> cipher = OpenSSL::Cipher::Cipher.new('AES-128-CBC')
=> #<OpenSSL::Cipher::Cipher:0x494c>
irb(main):005:0> digest = OpenSSL::Digest.new('sha256', 'digestdata')
=> #<OpenSSL::Digest: c8221a4fe5790b064e1f3de6f73493f3dab005aa05f41eb220c84ba4ac9c1f0e>
irb(main):006:0> digest = OpenSSL::Digest::Digest.new('sha256', 'digestdata')                                                                                                                                      
Digest::Digest is deprecated; use Digest
=> #<OpenSSL::Digest::Digest: c8221a4fe5790b064e1f3de6f73493f3dab005aa05f41eb220c84ba4ac9c1f0e>
```

**Comment by maokomioko** [comment]
Here is full stack traces with the list of gem files.
https://gist.github.com/maokomioko/148e3b85c142f7f68f23
I'm using OS X 10.11 using zsh (same thing happens under bash).

rails s (with thin) works fine under development, only rails c ends up every time.

What I've tried to do so far:
* switching different rbx versions (2.5.8, recent head, head from august, 2.5.2),
* rubsl and rubysl-openssl downgrades (from 2.3.0 to 2.0.5 including every minor release),
* changing shell from zsh to bash (just in case),
* booting console under production env;

Disabling rubysl-openssl removes the problem, but obviously renders project unusable :)

**Comment by tak1n** [comment]
I've tried a fresh rails app but cannot reproduce it.
Can u paste me also the Gemfile so I can paste it and see if a specific gem is triggering the error.

**Comment by maokomioko** [comment]
@tak1n here it is https://gist.github.com/maokomioko/1cc0e1c6474ef9b2bacd

**Comment by tak1n** [comment]
https://github.com/rubysl/rubysl-openssl/commit/0941f31298ea80b525cd289f0df03788e6d61c3c overwrites #2 
I can not reproduce it on my system, but I bet reapplying this fix will resolve it for you.
